version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-prod
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # For production, don't expose MongoDB port to the host
    expose:
      - "27017"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-prod
    restart: always
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/game-library
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=7d
    # For production, don't expose backend port to the host
    expose:
      - "3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-prod
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    # For production, don't expose frontend port to the host
    expose:
      - "80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Add Nginx as a reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/www:/var/www/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local